services:
  db:
    image: postgres:16
    container_name: garage_db
    environment:
      POSTGRES_DB: garage_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: ./GarageManagement.API
    container_name: garage_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=garage_management;Username=admin;Password=password123
    ports:
feature/diwash-F1-F7-F12-F15
      - "5001:8080"

      - "5008:8080"
main
    depends_on:
      - db

volumes:
  pgdata: